### ISSUE TITLE
Showing more than 3 elements in CoverFlowView

### ISSUE THREAD

**Issue by Xonshiz** [AndreiMisiukevich/CardView#199]
Currently, the CoverFlowView shows elements like this :
![image](https://user-images.githubusercontent.com/13240567/58175047-e76eb980-7cbc-11e9-8aab-29f2d098c5fa.png)

Is it possible to show more than that? The issue is that I have a `ImageButton` with an image in it inside CoverFlow. And for some reason it looks weird (Can't maintain the aspect ratio). I wanted to shrink it down a little and show more elements.

**Comment by AndreiMisiukevich** [comment]
I think, you can preserve 3 items, but just put more images on one card

----------card0 --------------------card1------------------------card2---------
[(image)(image)(image)] - [(image)(image)(image)]  - [(image)(image)(image)]

**Comment by Xonshiz** [comment]
That won't work for me. I mean, won't work for what I'm trying to achieve.
Please refer to this wireframe : https://xd.adobe.com/view/7d0551f6-fd34-4a15-7a4d-64d63f5dc096-0b34/

I'm trying to achieve the one under the "Hot Items" in a Horizontal scroll. It looks exactly like what CoverFlow shows. But, for some reason, I can't get it to shrink the images down.

I've implemented it here : [Implemented CoverFlow](https://github.com/Xonshiz/CoManga/blob/master/src/comic_dl/comic_dl/Pages/manga/MangaListing.xaml#L57)

I might be doing something wrong here definitely.

**Comment by AndreiMisiukevich** [comment]
@Xonshiz ah ) ok)
Is it super urgent for you?) I can check it on my free time
That's fine to get sample

Btw, could you please put screenshot here ?

**Comment by AndreiMisiukevich** [comment]
also i suggest you to check my sample. You missed some necessary properties (Shift value and margins for your cards)

**Comment by Xonshiz** [comment]
No urgent. Take your time. I'll post the screenshots in a while. I'll check the shift value and margins as well. IIRC, I did put them there. But, they didn't work for some reason, so removed them and did some workaround.

Take your time in taking a look at this. No hurry.

**Comment by AndreiMisiukevich** [comment]
@Xonshiz is it your issue https://github.com/AndreiMisiukevich/CardView/issues/204 ?

**Comment by Xonshiz** [comment]
Not completely, but yes I do get those borders and stuff around as well.
But, I haven't set the Itemsource before appearing.



Thank You,
Dhruv Kanojia
(Github <https://github.com/Xonshiz>| Website <http://psychoticelites.com/>
| Twitter <https://twitter.com/Xonshiz> | LinkedIn
<https://in.linkedin.com/in/dhruvkanojia> | Google+
<https://plus.google.com/+DhruvKanojia>)

**Comment by AndreiMisiukevich** [comment]
https://github.com/Xonshiz/CoManga/blob/master/src/comic_dl/comic_dl/Pages/manga/MangaListing.xaml#L59 it's totally wrong

SelectedItem is model / bindingcontext of selected card, not event!

**Comment by AndreiMisiukevich** [comment]
also check settings there:

https://github.com/AndreiMisiukevich/CardView/blob/master/PanCardViewSample/PanCardViewSample/Views/CoverFlowSampleXamlView.xaml#L19-L27

You should set ShitfPositionValue and set Margin or Padding to your Card template

**Comment by AndreiMisiukevich** [comment]
really, check my sample and play with margin and ShiftValue
